/*
create table empresa_centro_costo (
	id_empresa_centro_costo int primary key,
	empresa varchar(250),
	centro_costo varchar(250)
);

insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (1,'LAS_CANAS','Ma.PA.ParN')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (2,'LAS_CANAS','Ma.PA.ParO')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (3,'LAS_CANAS','MAC.COND.P')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (4,'LAS_CANAS','MAC.COND.V')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (5,'LAS_CANAS','MAC.TRONC.')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (6,'LAS_CANAS','PAII.88.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (7,'LAS_CANAS','PAII88.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (8,'LAS_CANAS','PAII96.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (9,'LAS_CANAS','PAII96.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (10,'LAS_CANAS','PALTO64.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (11,'LAS_CANAS','PALTO64.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (12,'LAS_CANAS','TER.P.ALTO')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (13,'HUALPEN','HP2.DP.7A2')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (14,'HUALPEN','HP2.VT.7A2')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (15,'HUALPEN','HP3.DP.7A2')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (16,'HUALPEN','HP3.VT.7A2')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (17,'HUALPEN','HP80DP.7A2')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (18,'HUALPEN','HP80VT.7A2')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (19,'HUALPEN','MAC.7A2A3')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (20,'HUALPEN','MAC.7A2.')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (21,'SAN_RAMON','ADM.61.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (22,'SAN_RAMON','ADM.61.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (23,'SAN_RAMON','ADM62.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (24,'SAN_RAMON','ADM62.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (25,'SAN_RAMON','COR.III.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (26,'SAN_RAMON','COR80II.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (27,'SAN_RAMON','CORV.2.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (28,'SAN_RAMON','CORV.3.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (29,'SAN_RAMON','LOTE.F')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (30,'SAN_RAMON','MAC.CORCOV')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (31,'SAN_RAMON','MAC.LOTE.G')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (32,'SAN_RAMON','TER.CORCOV')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (33,'SAN_RAMON','TERR.OLIVI')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (34,'TERRAZAS','TDM.69.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (35,'TERRAZAS','TDM.69.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (36,'JP_COQUIMBO','ADM64DP.D1')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (37,'JP_COQUIMBO','ADM64VT.D1')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (38,'JP_COQUIMBO','LOTE.H')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (39,'JP_COQUIMBO','MAC.187VIV')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (40,'JP_COQUIMBO','MAC184.DEP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (41,'JP_COQUIMBO','MAC274EDIF')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (42,'JP_COQUIMBO','SSC60.E3DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (43,'JP_COQUIMBO','SSC60.E3VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (44,'JP_COQUIMBO','SSC64DP.D1')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (45,'JP_COQUIMBO','SSC64VT.D1')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (46,'JP_COQUIMBO','TERR.SSC')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (47,'JP_SA','BUIN135.VT')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (48,'JP_SA','BUIN.MAC2')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (49,'JP_SA','BUIN135.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (50,'JP_SA','BUIN172.DP')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (51,'JP_SA','ENSANCHE')
insert into empresa_centro_costo (id_empresa_centro_costo, empresa, centro_costo) values (52,'JP_SA','MAC.2A3')
*/